name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mayur1252
          password: Tingare@123
      - name: Build, tag, and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: mayur1252
          IMAGE_NAME: my-image
        run: |
          docker build -t mayur1252/mayursimage .
          docker push mayur1252/mayursimage:latest
